name: Coverage automation

on:
  push:
    branches:
    - "develop"
    
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup scala
      uses: olafurpg/setup-scala@v14
      with:
        java-version: "adopt@1.16"
    - name: Build and Run coverage
      run: sbt -v -Dfile.encoding=UTF-8 +clean +coverage +test +coverageReport
    - name: Upload Scoverage coverage report
      uses: actions/upload-artifact@v3
      with:
        name: scoverage-report
        path: target/scala-3.2.1/scoverage-report/
