name: Release after tag

on:
  push:
    tags:
      - "v[1-9]+.[0-9]+.[0-9]+"

jobs:
  ubuntu_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: "adopt@1.16"
      - name: Deploy
        run: sbt -v -Dfile.encoding=UTF-8 -J-Xms2048m -J-Xmx4096m +assembly
      - name: Rename deployed file
        run: mv target/scala-3.2.1/caw.jar target/scala-3.2.1/caw-linux.jar
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: linux-version
          path: target/scala-3.2.1/caw-linux.jar
  
  macos_build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: "adopt@1.16"
      - name: Deploy
        run: sbt -v -Dfile.encoding=UTF-8 -J-Xms2048m -J-Xmx4096m +assembly
      - name: Rename deployed file
        run: mv target/scala-3.2.1/caw.jar target/scala-3.2.1/caw-macos.jar
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: macos-version
          path: target/scala-3.2.1/caw-macos.jar
  
  windows_build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: "adopt@1.16"
      - name: Deploy
        run: sbt -v -Dfile.encoding=UTF-8 -J-Xms2048m -J-Xmx4096m +assembly
        shell: bash
      - name: Rename deployed file
        run: mv target/scala-3.2.1/caw.jar target/scala-3.2.1/caw-windows.jar
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: windows-version
          path: target/scala-3.2.1/caw-windows.jar

  release:
    runs-on: ubuntu-latest
    needs:
      - ubuntu_build
      - macos_build
      - windows_build
    steps:
      - name: Download workflow artifacts
        uses: actions/download-artifact@v3
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            linux-version/caw-linux.jar
            macos-version/caw-macos.jar
            windows-version/caw-windows.jar
