name: Report generation

on:
  push:
    branches:
    - "main"
    paths: 
    - "report/**"
    
jobs:
  Generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create file list
        id: files_list
        run: |
          cd report
          echo "::set-output name=files::$(printf 'report/%s ' *.md)"
      - name: Convert with pandoc
        uses: docker://pandoc/latex:2.9
        with:
          args: >-
            -f markdown+raw_attribute+tex_math_dollars
            -t pdf
            -o report.pdf
            -N
            --toc
            --metadata-file=report/metadata.yml
            --resource-path=report
            ${{ steps.files_list.outputs.files }}
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: report
          path: report.pdf
