name: Testing automation

on:
  push:
    branches-ignore: 
    - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TERM: dumb
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup scala
        uses: olafurpg/setup-scala@v12
        with:
          java-version: "adopt@1.16"
      - name: Check for scalafmt conformance in files
        run: sbt -v -Dfile.encoding=UTF-8 +scalafmtCheck
      - name: Check for scalafmt conformance in test files
        run: sbt -v -Dfile.encoding=UTF-8 +test:scalafmtCheck
      - name: Build and Test
        run: sbt -v -Dfile.encoding=UTF-8 +test
